### ISSUE TITLE
updateById is vulnerable to SQL injection attacks

### ISSUE THREAD

**Issue by JasonTypesCodes** [mvolkmann/mysql-easier#8]
Discovered this while looking into #7 

updateById takes values passed in and converts them to a string representation of those values before passing them to the database.  I believe this makes it possible to execute a SQL injection attack by passing a SQL statement in as a string value.  These queries should instead be parameterized.  I also think that fixing this will fix #7.

**Comment by mvolkmann** [comment]
I'm working on a fix for this.
